### PR TITLE
Combine screenshots in README into a gif

### LINKED ISSUE #181: Combine screenshots in README into a gif
**Is your feature request related to a problem? Please describe.**
Combine screenshots in README into a GIF
It would be better to use updated screenshots for develop branch.

### PR DESCRIPTION
**Pull request by andrasbacsai**
Fixes #181 

Changes proposed in this pull request:
- Uploaded new gif to root
- Updated README.md with relative path

### CODE REVIEW

**Comment by andrasbacsai** [comment]
Not sure if I did it right. Please take a look and let me know.

**Comment by jesusbibieca** [comment]
Hey @andrasbacsai Thank you for contributing. I hope that you stick around and keep on contributing.

There is one thing that needs to be changed. It must be an absolute path and not relative, otherwise, it can cause issues displaying the image on the electron project (our app is featured in electron and it uses absolute paths to show the images in their site).

**Comment by jesusbibieca** [comment]
Also, the gif can be saved in the `assets/images` directory

**Comment by andrasbacsai** [comment]
Maybe I do not understand correctly the way how this works, but should I use your repository name as the link to the gif (https://github.com/abahmed/Deer/assets/images/screenshots.gif) in the README.md, even it does not exists in your repository at the moment, only after the merge? Or is there a way to store it in https://user-images.githubusercontent.com or raw.githubusercontent.com?

**Comment by jesusbibieca** [comment]
Don't worry if there is something that you don't understand. We are here to help. If you change the image to be stored in the images folder yes you can just do 
https://github.com/abahmed/Deer/assets/images/screenshots.gif After this is merged it should work ok... You can also try it first on your repo with your username instead of abahmed on the URL 👌

**Comment by andrasbacsai** [comment]
Cool. Thanks and how can I store it like you did in the current screenshots (https://user-images.githubusercontent.com)?

**Comment by abahmed** [comment]
@andrasbacsai Just upload it somewhere and it will have this link (https://github.com/RWTH-EBC/AixLib/wiki/How-to:-Add-images-to-the-Wiki)

**Pull request merged**
