### PR TITLE
Add About Us component (WIP)

### LINKED ISSUE #176: Add about us component
**Is your feature request related to a problem? Please describe.**
Add about us component contains Deer's contributors and Deer's logo too. You can just start a simple one, then it could be improved. @jesusbibieca @enzo-beltrami Any thought for the layout?

### PR DESCRIPTION
**Pull request by festMikolaj**
Fixes #176.

Changes proposed in this pull request:
- added electron-about-window

It should opens when you click Deer logo in header component, but its blank and there is error message in the devtools:

index.js:25 Uncaught TypeError: Cannot read property 'getName' of undefined
- at detectPackageJson (index.js:25)
- at injectInfoFromPackageJson (index.js:46)
- at openAboutWindow (index.js:133)
- at onClick (Header.js:54)

### CODE REVIEW

**Comment by abahmed** [comment]
Hi @festMikolaj,
Firstly, you need to add about-window package using command
`npm install --save about-window`


Then you need to use IPC signaling, instead of using Electron's code inside our app. See this example when user clicks close button, this what happens in order
1- https://github.com/abahmed/Deer/blob/develop/main.js#L89
2- https://github.com/abahmed/Deer/blob/develop/app/entry.js#L24
3- https://github.com/abahmed/Deer/blob/develop/main.js#L165

**Comment by festMikolaj** [comment]
Thanks @abahmed, I'm going to work on this now!

**Comment by jesusbibieca** [comment]
Hey @festMikolaj I like the idea of this opening from the setting component. Maybe having different options like `Language` to change languages and another option `About us` and trigger this. Or any other way that you might prefer. Maybe a `btn` at the bottom for about us.

**Comment by abahmed** [comment]
Done in PR #222

**Pull request closed without merging**
